version: '3.1'
services: 
  # database - MongoDB
  mongodb:
    image: mongo
    restart: always
    env_file: ./.env
    
    ports: 
      - $MONGOPORT:$MONGODOCKERPORT
    
    networks:
      - my-network
networks:
  my-network: